#!/system/bin/sh
# flashit: command-line shortcut to the work dir
# osm0sis @ xda-developers

flashit=/data/local/FlashIt;
bb=$flashit/bin/busybox;

case $1 in
  --restore)
    # fix shortcut script
    imgmnt=$(su -c "(ls -d /magisk || ls -d /sbin/.core/img || ls -d /sbin/.magisk/img || ls -d /data/adb/modules) 2>/dev/null");
    test "$imgmnt" && rbmsg=' \(reboot required\)';
    su -c " \
      if [ -e /su ]; then \
        cp -pf $flashit/bin/flashit /su/bin/flashit; \
      elif [ -e /sbin/supersu ]; then \
        cp -pf $flashit/bin/flashit /sbin/supersu/bin/flashit; \
      elif [ "$imgmnt" ]; then \
        test -e /magisk && imgmnt=/magisk || imgmnt=/sbin/.core/img; \
        mkdir -p $imgmnt/flashit/system/bin; \
        cp -pf $flashit/bin/flashit $imgmnt/flashit/system/bin/flashit; \
        cp -pf $flashit/bin/module.prop $imgmnt/flashit/module.prop; \
        touch $imgmnt/flashit/auto_mount $imgmnt/flashit/update; \
        chcon -hR 'u:object_r:system_file:s0' $imgmnt/flashit; \
        rbmsg=' (reboot required)'; \
      else \
        $bb mount -o rw,remount -t auto /system; \
        rm -f /system/xbin/flashit; \
        cp -pf $flashit/bin/flashit /system/xbin/flashit; \
        $bb mount -o ro,remount -t auto /system; \
      fi; \
      echo "flashit: shortcut restored!$rbmsg"; \
    ";
  ;;
  --uninstall)
    # remove FlashIt and shortcut script
    su -c " \
      if [ -e /su -o -e /sbin/supersu -o -e /magisk -o -e /sbin/.core/img -o -e /sbin/.magisk/img -o -e /data/adb/modules ]; then \
        rm -rf $flashit /su/bin/flashit /sbin/supersu/bin/flashit /magisk/flashit /sbin/.core/img/flashit /sbin/.magisk/img/flashit /data/adb/modules/flashit; \
      else \
        $bb mount -o rw,remount -t auto /system; \
        rm -rf $flashit /system/xbin/flashit; \
        $bb mount -o ro,remount -t auto /system; \
      fi; \
      echo 'flashit: uninstall complete!'; \
    ";
  ;;
  --help)
    # print help for shortcut command
    echo "usage: flashit [--restore|--uninstall|--help]";
  ;;
  *)
    # go local and request root
    cd $flashit;
    PATH="$PATH:$flashit" su;
  ;;
esac;

