#!/system/bin/sh
# odex: automate odexing specific files, or core system framework
# osm0sis @ xda-developers

case $PATH in
*/system/xbin*) ;;
*) export PATH=$PATH:/system/xbin:/system/bin ;;
esac
if [ -z "$BOOTCLASSPATH" ]; then
	export BOOTCLASSPATH=/system/framework/core.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/framework2.jar:/system/framework/framework-pac.jar:/system/framework/telephony-common.jar:/system/framework/telephony-msim.jar:/system/framework/voip-common.jar:/system/framework/mms-common.jar:/system/framework/android.policy.jar:/system/framework/services.jar:/system/framework/apache-xml.jar:/system/framework/webviewchromium.jar
fi

case $1 in
--help | "")
	echo "Usage: odex [-c] FILE1 [FILE2 ...]"
	echo "odexes supplied files and/or system frameworks.\n"
	echo "  -c, --core  odex core system framework files"
	echo "      --help  Display this help and exit"
	return
	;;
--core | -c)
	echo "odex: odexing core system framework files..."
	list="/system/framework/core.jar /system/framework/conscrypt.jar /system/framework/okhttp.jar /system/framework/core-junit.jar /system/framework/bouncycastle.jar /system/framework/ext.jar /system/framework/framework.jar /system/framework/framework2.jar /system/framework/framework-pac.jar /system/framework/telephony-common.jar /system/framework/telephony-msim.jar /system/framework/voip-common.jar /system/framework/mms-common.jar /system/framework/android.policy.jar /system/framework/services.jar /system/framework/apache-xml.jar /system/framework/webviewchromium.jar"
	core=1
	;;
*)
	echo "odex: odexing supplied files..."
	list="$*"
	;;
esac

mount -o remount,rw /system 2>/dev/null
for file in $list; do
	if [ -f $file ]; then
		noPath=$(basename $file)
		[ $file == $noPath ] && file=$(pwd)/$noPath
		odexFile=${file%\.*}.odex
		dalvikFile=$(echo ${file//\//@} | cut -c 2-)@classes.dex
		case $noPath in
		*.jar | *.apk)
			if [ ! $core ]; then
				case $noPath in
				core.jar | conscrypt.jar | okhttp.jar | core-junit.jar | bouncycastle.jar | ext.jar | framework.jar | framework2.jar | framework-pac.jar | telephony-common.jar | telephony-msim.jar | voip-common.jar | mms-common.jar | android.policy.jar | services.jar | apache-xml.jar | webviewchromium.jar)
					echo "$noPath is a core framework file, skipping"
					continue
					;;
				esac
			fi
			if [ -f $odexFile ]; then
				echo "$file is already odexed"
			else
				echo "$file"
				dexopt-wrapper $file $odexFile >/dev/null
				zip -d $file classes.dex >/dev/null
				rm -f /data/dalvik-cache/$dalvikFile
				chmod 644 $odexFile
			fi
			;;
		*)
			echo "$file is not valid"
			;;
		esac
	else
		echo "$file does not exist"
	fi
done
mount -o remount,ro /system 2>/dev/null
