#!/system/bin/sh

umask 077

# DEBUG=1
ssh_dir=$ex/ssh
DSA_KEY="${ssh_dir}"/ssh_host_dsa_key
DSA_PUB_KEY="${ssh_dir}"/ssh_host_dsa_key.pub
RSA_KEY="${ssh_dir}"/ssh_host_rsa_key
RSA_PUB_KEY="${ssh_dir}"/ssh_host_rsa_key.pub
AUTHORIZED_KEYS="${ssh_dir}"/authorized_keys
DEFAULT_AUTHORIZED_KEYS=/system/etc/security/authorized_keys.default

sshd_ex=$(command -v sshd)
if [ ! -f $DSA_KEY ]; then
	ssh-keygen -t dsa -f $DSA_KEY -N ""
	chmod 600 /$DSA_KEY
	chmod 644 $DSA_PUB_KEY
fi

if [ ! -f $RSA_KEY ]; then
	ssh-keygen -t rsa -f $RSA_KEY -N ""
	chmod 600 /$RSA_KEY
	chmod 644 $RSA_PUB_KEY
fi
[[ -e /system/etc/ssh/ssh_host_dsa_key ]] || cp -av "${ssh_dir}"/* /system/etc/ssh/
##############Phase2######################
ssh_dir=/system/etc/ssh

DSA_KEY="${ssh_dir}"/ssh_host_dsa_key
DSA_PUB_KEY="${ssh_dir}"/ssh_host_dsa_key.pub
RSA_KEY="${ssh_dir}"/ssh_host_rsa_key
RSA_PUB_KEY="${ssh_dir}"/ssh_host_rsa_key.pub
AUTHORIZED_KEYS="${ssh_dir}"/authorized_keys
DEFAULT_AUTHORIZED_KEYS=/system/etc/security/authorized_keys.default
if [ ! -f $DSA_KEY ]; then
	ssh-keygen -t dsa -f $DSA_KEY -N ""
fi
	chmod 600 /$DSA_KEY
	chmod 644 $DSA_PUB_KEY

if [ ! -f $RSA_KEY ]; then
	ssh-keygen -t rsa -f $RSA_KEY -N ""
fi
	chmod 600 /$RSA_KEY
	chmod 644 $RSA_PUB_KEY

if [[ ! -f $AUTHORIZED_KEYS && -f $DEFAULT_AUTHORIZED_KEYS ]]; then
	cat $DEFAULT_AUTHORIZED_KEYS >$AUTHORIZED_KEYS
fi
$sshd_ex -A


if [ "1" == "$DEBUG" ]; then
	# run sshd in debug mode and capture output to logcat
	/system/bin/logwrapper /system/bin/sshd -f /system/etc/ssh/sshd_config -D -d
else
	# don't daemonize - otherwise we can't stop the sshd service
	$sshd_ex -f /system/etc/ssh/sshd_config -D
fi
